
trigger:
- main

pool: omkar-hcl

stages:
 - stage: install
   jobs: 
    - job: install-terraform
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

  
