
trigger:
- main

pool: omkar-hcl

stages:
 - stage: install
   jobs: 
    - job: installterraform
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '1.8.4'
    - job: terraforminit
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: "$(System.DefaultWorkingDirectory)/HCL-OM"
          backendServiceArm: 'HCL-infrasc'
          backendAzureRmStorageAccountName: 'omkarhcl123'
          backendAzureRmContainerName: 'omkarcont'
          backendAzureRmKey: 'terraform.tfstate'
     

  
