trigger: none
pool : omkar-hcl

stages:
 - stage: install
   jobs:
    - job: terraforminstall
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: 'HCL-infrasc'
          backendAzureRmStorageAccountName: 'omkarhcl123'
          backendAzureRmContainerName: 'omkarcont'
          backendAzureRmKey: 'path.tfstate'
     
      


