
trigger:
- main

pool: omkar-hcl

stages:
 - stage: install
   jobs: 
    - job: installterraform
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      
 - stage: init
   jobs:
    - job: terraforminit
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'C:\Users\OMKAR SINGH\OneDrive\Documents\Downloads\azure document sof\vsts-agent-win-x64-4.260.0\_work\1\s\parent'
          backendServiceArm: 'HCL-infrasc'
          backendAzureRmStorageAccountName: 'omkarst3455'
          backendAzureRmContainerName: 'omkar'
          backendAzureRmKey: 'terraform.tfstate'

  
